### ISSUE TITLE
Set up to not join trollbox

### ISSUE THREAD

**Issue by benzmuircroft** [MKPLKN/trollbox#2]
How do I make this connect to a totally private room for use in my own application?

ty

**Comment by benzmuircroft** [comment]
figured it out, to use it in node server side

npm i "https://github.com/MKPLKN/trollbox" --save-dev

```
  const Keychain = require('keypear');
  const b4a = require('b4a');
  const { Trollbox, TrollboxClient } = await import('trollbox');

  const names = new Trollbox({
    seed: new Keychain({
      publicKey: b4a.from('139e83fecd863505184764bb139uca9dc7au7a9c124d54ec6ea9d272970fe99x', 'hex'),
      scalar: b4a.from('408f4se429897707252ad9cfe4x37a7567d20e4541742b8bcs87071d2dwa2248', 'hex')
    }),
    topic: Buffer.alloc(32).fill('usernames'),
    isRelay: true,
  });
  await names.start();
  names.on('connectionData', (stream, data) => {
    console.log(JSON.parse(names.decodeMessage(data)));
  });
  names.sendMessage('{"benz":"xxxx"}');
```

**Comment by benzmuircroft** [comment]
but I don't understand the client nor the ramifications of only using this server over and over in each peer

**Comment by MKPLKN** [comment]
There are three parts
- UI (the client)
- Hosting server (the relay)
- P2P network

The UI connects to the relay, and the relay connects to the P2P network. If you have a UI that allows users to access the P2P network, then the relay is required. It's used for each peer, but only for those using the browser. Similarly, in typical WebSocket-based applications, the connection is made with the hosting server between each user.

**Comment by MKPLKN** [comment]
Closing this since this is figured out
https://github.com/MKPLKN/trollbox/issues/2#issuecomment-1836484227
